"""Record example responses for contracts/fixtures/<name>.json from the sample dataset.

Each fixture is {_sample, _note, endpoint, request, response}; tests replay the
request against MOCK=1 and require an identical response.
"""
import json
from pathlib import Path

from fastapi.testclient import TestClient

NOTE = "Invented [ЖИШЭЭ] SAMPLE data generated by scripts/seed_demo.py. Not real legal content."
LABOR = "khodolmoriin-tukhai-khuuli"
OSH = "khodolmoriin-ayuulgui-baidal-eruul-akhuin-tukhai-khuuli"

# name -> (method, path, query, body)
REQUESTS = {
    "health": ("GET", "/api/health", {}, None),
    "laws_list": ("GET", "/api/laws", {}, None),
    "law_detail": ("GET", f"/api/laws/{LABOR}", {}, None),
    "law_articles": ("GET", f"/api/laws/{LABOR}/articles", {}, None),
    "law_connections": ("GET", f"/api/laws/{LABOR}/connections", {}, None),
    "article_connections": ("GET", f"/api/articles/{LABOR}:80/connections", {}, None),
    "article_impact": ("POST", f"/api/articles/{LABOR}:80.1/impact", {},
                       {"new_text": "[ЖИШЭЭ] Ажилтны долоо хоногийн ажлын хэвийн цаг 38 цагаас хэтрэхгүй байна.",
                        "depth": 2}),
    "impact": ("POST", "/api/impact", {},
               {"law_id": "khodolmor-erkhleltiig-demjikh-tukhai-khuuli",
                "new_name": "Хөдөлмөр эрхлэлт, ур чадварыг дэмжих тухай хууль", "depth": 2}),
    "drafts_list": ("GET", "/api/drafts", {}, None),
    "draft_detail": ("GET", "/api/drafts/draft-sample-labor-001", {}, None),
    "draft_gap": ("GET", "/api/drafts/draft-sample-labor-001/gaps", {}, None),
    "article_international": ("GET", f"/api/articles/{LABOR}:80/international", {}, None),
    "article_amendment": ("GET", f"/api/articles/{LABOR}:104/amendment", {}, None),
    "relation_detail": ("GET", f"/api/articles/{LABOR}:80.1/relations/{OSH}:12.1", {}, None),
    "search": ("GET", "/api/search", {"q": "ажлын цаг"}, None),
}


def replay(client: TestClient, name: str):
    method, path, query, body = REQUESTS[name]
    return client.request(method, path, params=query or None, json=body)


def record_fixtures(sample_processed: Path, fixtures_dir: Path) -> list[str]:
    from .. import config, deps
    from ..main import app

    config.MOCK = True
    config.FIXTURES_DIR = sample_processed.parent
    deps._store.cache_clear()
    client = TestClient(app)
    written = []
    for name, (method, path, query, body) in REQUESTS.items():
        r = replay(client, name)
        r.raise_for_status()
        doc = {"_sample": True, "_note": NOTE, "endpoint": f"{method} {path}",
               "request": {"query": query, "body": body}, "response": r.json()}
        (fixtures_dir / f"{name}.json").write_text(json.dumps(doc, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        written.append(name)
    return written
